image: python:3.9-alpine

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH
    
pages:
  script:
  - python3.9 -m pip install poetry --user
  - python3.9 -m poetry install
  - python3.9 -m poetry run sphinx-build -b html doc/source public
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
